version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /home/mark/sonarr:/config
      - /mnt/media:/plex
      - /mnt/data:/data
      - /mnt/torrent:/torrent
    ports:
      - 8989:8989
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8989 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
