version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    ports:
      - 8181:8181
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8181 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
