version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/container_data/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:5055 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
