version: '3'

services:
  readarr:
    image: hotio/readarr:latest
    container_name: readarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/container_data/readarr/config:/config
      - /mnt/container_data/readarr/media:/media
    ports:
      - 6767:7878
