version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /home/mark/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:9696 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
