version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - /mnt/data/torrent/data:/data
            - /mnt/data/torrent/config:/config
        environment:
            - OPENVPN_PROVIDER=SURFSHARK
            - OPENVPN_CONFIG=us-chi.prod.surfshark.com_udp
            - OPENVPN_USERNAME=CCAbbSjrdJLTMtytcHvhJdYT
            - OPENVPN_PASSWORD=bmtGaUQd4bBAjRbajS9p4gqH
            - PUID=1000
            - PGID=1000
            - TRANSMISSION_WEB_UI=transmissionic
            - LOCAL_NETWORK=10.0.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9999:9091'
            - '51413:51413'
            - '51413:51413/udp'
        image: haugene/transmission-openvpn
