version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /mnt/container_data/prometheus:/etc/prometheus
      - /mnt/container_data/prometheus/prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/mnt/container_data/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/mnt/container_data/grafana
    restart: unless-stopped
