version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9092:9090"
    volumes:
      - /mnt/container_data/prometheus:/etc/prometheus
      - /mnt/container_data/prometheus/prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/mnt/container_data/prometheus/prometheus.yml"
