version: '3'
services:
  ersatztv:
    container_name: ersatztv
    environment:
      - TZ=America/Chicago
    ports:
      - '8409:8409'
    volumes:
      - '/mnt/container_data/data/erstattv/config:/root/.local/share/ersatztv'
      - '/mnt/data/media:/path/to/local/media:ro'
    restart: unless-stopped
    image: 'jasongdove/ersatztv:develop-nvidia'
