version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /mnt/container_data/grafana:/var/lib/grafana
    restart: always

volumes:
  grafana_data:
