version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
  volumes:
      - /mnt/container_data/radarr:/config
      - /mnt/data/media/movies:/data/media/movies
      - /mnt/data:/data
      - /mnt/data:/downloads/completed/Movies
    ports:
      - 7878:7878
    restart: unless-stopped
