version: "3.4"
services:
  requestrr:
    image: thomst08/requestrr
    hostname: requestrr
    container_name: requestrr
    ports:
    - 4545:4545
    volumes:
    - /home/mark/container_data/requestrr:/root/config
    restart: unless-stopped
