version: "3.4"
services:
  requestrr:
    image: thomst08/requestrr
    hostname: requestrr
    container_name: requestrr
    ports:
    - 4545:4545
    volumes:
    - /home/mark/container_data/requestrr:/root/config
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://10.0.10.211:4545 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
