version: "2.1"
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
      - NZBGET_USER=mark #optional
      - NZBGET_PASS=marcus21Z! #optional
    volumes:
      - /mnt/container_data/nzbget:/config
      - /mnt/data:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
